// Presentation-only options. These values never configure analysis or a user's report.
export const themes = [
  {
    id: 'porcelain',
    name: '포슬린 블루',
    note: '여백이 넓고 선명한 기본형',
    colors: [
      '#f4f7fc',
      '#ffffff',
      '#edf3ff',
      '#152d50',
      '#50647e',
      '#245be0',
      '#d6e1f1',
      '#6ea7ff',
    ],
    eye: 'sapphire',
    pyramid: 'crystal',
    effect: 'orbit',
  },
  {
    id: 'cobalt',
    name: '코발트 포커스',
    note: '강한 파랑과 명확한 대비',
    colors: [
      '#edf2ff',
      '#ffffff',
      '#e5edff',
      '#112355',
      '#50618a',
      '#1748d4',
      '#cdd8f5',
      '#508bff',
    ],
    eye: 'cobalt',
    pyramid: 'cobalt',
    effect: 'ribbon',
  },
  {
    id: 'glacier',
    name: '글레이셔',
    note: '얼음처럼 맑은 하늘색',
    colors: [
      '#f0f9ff',
      '#ffffff',
      '#e4f5ff',
      '#123a54',
      '#496c82',
      '#0677b9',
      '#cce5f2',
      '#58c8f6',
    ],
    eye: 'glacier',
    pyramid: 'ice',
    effect: 'constellation',
  },
  {
    id: 'ink',
    name: '잉크 & 페이퍼',
    note: '짙은 남색과 차분한 문서',
    colors: [
      '#eef2f7',
      '#ffffff',
      '#e8eef8',
      '#15233d',
      '#52617a',
      '#244577',
      '#d2dce9',
      '#7ea8ee',
    ],
    eye: 'midnight',
    pyramid: 'ink',
    effect: 'prism',
  },
  {
    id: 'periwinkle',
    name: '페리윙클',
    note: '보랏빛을 살짝 더한 파랑',
    colors: [
      '#f4f5ff',
      '#ffffff',
      '#eeefff',
      '#282e58',
      '#5d6585',
      '#4b5bc4',
      '#dbdff5',
      '#929ff1',
    ],
    eye: 'periwinkle',
    pyramid: 'prism',
    effect: 'comet',
  },
  {
    id: 'azure',
    name: '애저 라인',
    note: '흰 바탕 위 또렷한 푸른 선',
    colors: [
      '#f7fbff',
      '#ffffff',
      '#eaf5ff',
      '#163451',
      '#506c83',
      '#0c69c7',
      '#d0e5f7',
      '#56a7f4',
    ],
    eye: 'sapphire',
    pyramid: 'ice',
    effect: 'ribbon',
  },
];

export const layouts = [
  { id: 'focus', name: '포커스', note: '요약과 피라미드를 나란히', icon: 'split' },
  { id: 'editorial', name: '에디토리얼', note: '읽는 흐름에 집중한 문서', icon: 'document' },
  { id: 'compass', name: '컴퍼스', note: '피라미드 주변에 네 평가축', icon: 'sidebar' },
  { id: 'stacked', name: '챕터', note: '위에서 아래로 한 단계씩', icon: 'rows' },
  { id: 'briefing', name: '브리핑', note: '핵심 정보를 한눈에 비교', icon: 'columns' },
  { id: 'studio', name: '스튜디오', note: '큰 입체 그래픽과 핵심 요약', icon: 'center' },
];

export const eyes = [
  {
    id: 'sapphire',
    name: '사파이어 라인',
    note: '백색 배경 · 청색 미세선',
    fiber: '#2056bf',
    highlight: '#9ad6ff',
    outline: '#365b91',
    background: '#f4f8ff',
    panel: '#ffffff',
    text: '#17335b',
  },
  {
    id: 'cobalt',
    name: '코발트 나이트',
    note: '짙은 파랑 · 백색 빛',
    fiber: '#5996ff',
    highlight: '#ffffff',
    outline: '#c1daff',
    background: '#0c2147',
    panel: '#102b55',
    text: '#edf5ff',
  },
  {
    id: 'glacier',
    name: '아이스 블루',
    note: '아주 옅은 파랑 · 청록 빛',
    fiber: '#0879ae',
    highlight: '#9ae8ff',
    outline: '#426e89',
    background: '#effbff',
    panel: '#ffffff',
    text: '#12415d',
  },
  {
    id: 'midnight',
    name: '문라이트',
    note: '남색 배경 · 은청색 선',
    fiber: '#a3c5fa',
    highlight: '#ffffff',
    outline: '#a4bad8',
    background: '#101b30',
    panel: '#172640',
    text: '#edf5ff',
  },
  {
    id: 'periwinkle',
    name: '블루 오팔',
    note: '백색 배경 · 보랏빛 파랑',
    fiber: '#606ed4',
    highlight: '#cbdfff',
    outline: '#586b9b',
    background: '#f6f6ff',
    panel: '#ffffff',
    text: '#2c396c',
  },
];

export const pyramids = [
  {
    id: 'crystal',
    name: '클리어 사파이어',
    note: '맑은 유리 · 파랑 → 하늘색',
    base: '#3677e4',
    projected: '#72c8f5',
    glass: '#d9ecff',
    edge: '#8bacd2',
    background: '#edf5ff',
  },
  {
    id: 'cobalt',
    name: '코발트 크리스털',
    note: '청색 유리 · 파랑 → 은백색',
    base: '#3167d9',
    projected: '#d9efff',
    glass: '#94b9f1',
    edge: '#5780b9',
    background: '#142c51',
  },
  {
    id: 'ice',
    name: '아이스 프리즘',
    note: '얼음빛 유리 · 청록 → 파랑',
    base: '#41a3ca',
    projected: '#386ccf',
    glass: '#c6f0fa',
    edge: '#6dabc3',
    background: '#f1fcff',
  },
  {
    id: 'ink',
    name: '실버 잉크',
    note: '남색 유리 · 은청색 → 백색',
    base: '#92b8ed',
    projected: '#f2f8ff',
    glass: '#a6c4eb',
    edge: '#b5d1f3',
    background: '#14223b',
  },
  {
    id: 'prism',
    name: '오팔 글라스',
    note: '옅은 청색 유리 · 파랑 → 라벤더',
    base: '#5b8bd8',
    projected: '#9295e6',
    glass: '#dde7ff',
    edge: '#97a9d5',
    background: '#f2f4ff',
  },
];

export const effects = [
  {
    id: 'orbit',
    name: '블루 오빗',
    note: '파란 입자가 회전하며 테두리로 모임',
    primary: '#377bed',
    secondary: '#98d6ff',
    glow: '#ffffff',
    style: 'orbit',
  },
  {
    id: 'ribbon',
    name: '화이트 리본',
    note: '흰색·파란 곡선이 보고서를 감쌈',
    primary: '#2365d7',
    secondary: '#b2dbff',
    glow: '#ffffff',
    style: 'ribbon',
  },
  {
    id: 'constellation',
    name: '아이스 컨스텔레이션',
    note: '차가운 별빛이 윤곽을 연결',
    primary: '#158bc1',
    secondary: '#73d4f5',
    glow: '#e7fbff',
    style: 'constellation',
  },
  {
    id: 'prism',
    name: '실버 프리즘',
    note: '은백색 광선이 면과 모서리를 형성',
    primary: '#497bbb',
    secondary: '#accbf2',
    glow: '#ffffff',
    style: 'prism',
  },
  {
    id: 'comet',
    name: '오팔 코멧',
    note: '푸른 혜성 궤적과 가는 테두리 빛',
    primary: '#6578da',
    secondary: '#a4baff',
    glow: '#f5f7ff',
    style: 'comet',
  },
];

export const groups = {
  theme: themes,
  layout: layouts,
  eye: eyes,
  pyramid: pyramids,
  effect: effects,
};
export const defaults = {
  theme: 'porcelain',
  layout: 'focus',
  eye: 'sapphire',
  pyramid: 'crystal',
  effect: 'orbit',
};
export function selectionFromSearch(search) {
  const params = new URLSearchParams(search);
  return Object.fromEntries(
    Object.entries(groups).map(([key, values]) => [
      key,
      values.some((v) => v.id === params.get(key)) ? params.get(key) : defaults[key],
    ]),
  );
}
