import { escapeHtml as e, icon } from '../../shared/components/ui.js';

export function analysisReport(draft) {
  const r = draft.report;
  const criteria = r.criteria || [];
  const matches = r.matches || [];
  const statusLabel = { confirmed: '근거 확인', partial: '추가 확인', missing: '근거 부족' };
  const criteriaView = criteria.map(c => `<div class="criterion"><div><span>${e(c.label)}</span><strong>${e(c.score)} / ${e(c.max_score)}</strong></div><progress value="${Number(c.score) || 0}" max="${Number(c.max_score) || 1}" aria-label="${e(c.label)}"></progress></div>`).join('');
  return `<div class="result-toolbar"><div><span class="completion">${icon('check',17)} 분석 완료</span><span class="result-date">${e(draft.created_at || '')}${draft.created_at ? ' KST' : ''}</span></div><div><button id="print-report" type="button" class="button secondary compact">리포트 인쇄</button><a class="button secondary compact" href="#/questions">${icon('refresh',17)} 답변 수정 · 재분석</a></div></div><div class="result-layout"><aside class="report-sidebar"><h2>이번 모의지원</h2><div class="sidebar-position"><span class="sidebar-mark">${icon('briefcase',19)}</span><strong>${e(draft.company)}</strong><p>${e(draft.role)}</p><span class="small-note">분석 완료</span></div>${[['overview','핵심 요약'],['readiness','지원 준비도'],['evidence','공고별 근거'],['priorities','우선 보완 사항'],['interview','예상 면접 질문']].map(([id, label]) => `<a href="#/result" data-section="${id}">${label}</a>`).join('')}<div class="sidebar-bottom"><a href="#/resume">이력서 수정</a><a href="#/job">지원 공고 수정</a></div></aside><article data-resume-score-card="true" class="resume-score-card" tabindex="0" aria-label="모의지원 분석 결과"><header class="report-hero" id="overview"><div class="report-position"><span class="company-initial large">${e(draft.company?.slice(0,1))}</span><div><p>${e(draft.company)}</p><h1>${e(draft.role)}</h1></div></div><div class="verdict"><h2>${e(r.verdict)}</h2><span class="badge green">준비도 ${e(r.score)}점</span></div><h3>핵심 요약</h3><p class="report-summary">${e(r.summary)}</p></header><div class="report-body">
    <section class="report-section readiness-section" id="readiness"><h2>이대로 지원해도 될까요?</h2><p class="section-intro">이력서에 드러난 근거와 먼저 보완할 부분을 함께 확인하세요.</p><div class="readiness-grid"><div class="readiness-score"><div class="score-heading">${icon('report',42)}<div><span class="score-number">${e(r.score)}</span><span class="score-denominator"> / 100</span></div></div><h3>공고 기준 준비도</h3><p>입력된 근거를 정해진 기준으로 점검한 점수입니다. 실제 지원자 순위나 합격 확률이 아닙니다.</p><div class="score-criteria">${criteriaView}</div></div><div class="mail-preview"><div class="mail-heading">${icon('mail',21)}<h3>리크루터 메일 예시</h3><span class="badge neutral">가상 예시</span></div><p class="mail-subject">${e(r.recruiter_email?.subject)}</p><div class="mail-body">${e(r.recruiter_email?.body)}</div><p class="small-note">분석 결과로 구성한 연습용 메시지입니다. 실제 채용팀의 연락이 아닙니다.</p></div></div></section>
    <section class="report-section" id="evidence"><div class="section-heading"><h2>공고 요건과 연결되는 근거</h2><span class="badge neutral">${matches.length}개 항목</span></div><p class="section-intro">표현이 같아도 경험이 충분하다는 뜻은 아닙니다. 인용된 내용을 직접 확인하세요.</p><div class="evidence-list">${matches.map(m => `<div class="evidence-row"><div><span class="badge ${Object.hasOwn(statusLabel, m.status) ? m.status : 'partial'}">${statusLabel[m.status] || '추가 확인'}</span><h3>${e(m.requirement)}</h3></div><div>${m.evidence_items?.length ? m.evidence_items.map(item => `<div class="evidence-excerpt"><blockquote>${e(item.excerpt)}</blockquote><span class="source-label">출처 · ${e(item.source_label)}</span></div>`).join('') : '<p class="missing-copy">현재 입력 내용에서 연결되는 근거를 찾지 못했습니다.</p>'}</div></div>`).join('')}</div></section>
    <section class="report-section"><div class="findings-grid"><div><h2>잘 드러난 강점</h2><ul class="findings strengths">${(r.strengths || []).map(item => `<li>${icon('check',17)}<span>${e(item)}</span></li>`).join('')}</ul></div><div><h2>더 필요한 근거</h2><ul class="findings gaps">${(r.gaps || []).map(item => `<li><span class="gap-dot"></span><span>${e(item)}</span></li>`).join('')}</ul></div></div></section>
    <section class="report-section" id="priorities"><h2>지원 전, 이것부터 보완하세요.</h2><div class="priority-list">${(r.priorities || []).map((p, index) => `<div class="priority"><span>${index + 1}</span><div><h3>${e(p.title)}</h3><p>${e(p.detail)}</p></div></div>`).join('')}</div></section>
    <section class="report-section" id="interview"><h2>다음 대화에서 나올 수 있는 질문</h2><ol class="interview-list">${(r.questions || []).map(q => `<li>${e(q)}</li>`).join('')}</ol></section>
    <details class="methodology"><summary>점수는 어떻게 계산하나요?</summary><p>${e(r.methodology)}</p>${criteria.map(c => `<p><strong>${e(c.label)} (${e(c.max_score)}점)</strong><br>${e(c.detail)}</p>`).join('')}</details><div class="report-end"><p>좋은 지원서는, 확인할 수 있는 경험에서 시작됩니다.</p><a class="button primary" href="#/resume">이력서 보완하기 ${icon('arrow',18)}</a></div></div></article></div>`;
}
