import { escapeHtml as e, icon } from '../shared/components/ui.js';
import { resumeEditor } from '../features/resumes/resume.js';
import { jobEditor } from '../features/job-postings/job.js';
import { questionsEditor } from '../features/analysis/questions.js';
import { analysisReport } from '../features/analysis/report.js';

export function workspacePage(page, draft, questions) {
  if (page === 'result') return analysisReport(draft);
  if (page === 'job') return `<div class="page-heading"><div><h1>어떤 포지션에 지원하시나요?</h1><p>공고의 업무와 자격 요건을 내 이력서의 경험과 연결합니다.</p></div></div><div class="editor-layout">${jobEditor(draft)}<aside class="guide-panel"><div class="aside-icon">${icon('briefcase',27)}</div><h2>공고가 구체적일수록<br>근거도 명확해져요.</h2><p>회사 소개보다는 실제 담당 업무와 필수 역량이 담긴 내용을 입력해 주세요.</p><div class="attached-resume">${icon('check',18)}<div><strong>이력서 준비 완료</strong><p>${e(draft.filename || '직접 입력한 이력서')}<br>${(draft.resume_text?.length || 0).toLocaleString('ko-KR')}자</p></div></div><p class="small-note">다음 단계에서는 공고에 맞는 질문에 답하고, 한 번에 리포트를 확인합니다.</p></aside></div>`;
  if (page === 'questions') return `<div class="page-heading"><div><h1>조금 더 선명한 근거를 더해요.</h1><p>이력서에서 다 담지 못한 경험이 있다면 알려주세요.</p></div><span class="badge neutral">결과 확인 전 마지막 단계</span></div><div class="editor-layout">${questionsEditor(draft, questions)}<aside class="guide-panel"><div class="position-block"><span class="company-initial">${e(draft.company?.slice(0,1))}</span><p>${e(draft.company)}</p><h2>${e(draft.role)}</h2></div><div class="aside-separator"></div><h3>있는 경험만 적어주세요.</h3><p>추가 답변은 이력서와 구분해 결과에 표시합니다. 수치나 성과를 새로 만들어 적을 필요는 없어요.</p><p class="small-note">답변은 선택 사항입니다. 비워두면 이력서와 공고만으로 현재 상태를 점검합니다.</p></aside></div>`;
  return `<div class="page-heading"><div><h1>지원의 시작은,<br class="mobile-break"> 내 이력서부터.</h1><p>이력서를 불러오면 지원할 공고에 맞춰 준비 상태를 확인합니다.</p></div>${draft.resume_text ? '' : `<button id="example" class="button secondary compact" type="button">예시로 체험하기 ${icon('arrow',17)}</button>`}</div><div class="editor-layout">${resumeEditor(draft)}<aside class="guide-panel"><h2>모의지원까지,<br>세 단계면 충분해요.</h2><ol class="journey"><li class="current"><span>1</span><div><strong>이력서 입력</strong><p>내 경험과 성과를 준비해요.</p></div></li><li><span>2</span><div><strong>지원 공고 입력</strong><p>회사와 직무의 기준을 정해요.</p></div></li><li><span>3</span><div><strong>모의지원 확인</strong><p>근거를 보완하고 결과를 확인해요.</p></div></li></ol><div class="privacy-note">${icon('lock',20)}<p>입력한 이력서와 공고는 연결된 팀 API로 전송됩니다. 저장과 분석은 해당 서비스의 설정을 따릅니다.</p></div><p class="small-note">스캔한 PDF는 본문을 읽지 못할 수 있어요. 그럴 때는 텍스트를 직접 붙여넣어 주세요.</p></aside></div>${draft.resume_text ? '<div class="reset-form"><button id="clear-workspace" class="text-button" type="button">입력 내용과 결과 삭제</button></div>' : ''}`;
}
